server:
  port: 8083

spring:
  application:
    name: sample-kafka-producer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topic: test-topic

uok:
  service:
    name: sample-kafka-producer
  env: test
